# Personal setup for arch
---
- hosts: all
  sudo: yes
  remote_user: root
  vars:
    - ansible_python_interpreter: python2
  tasks:
    - name: Update package cache
      pacman: update_cache=yes

    - name: Install packages
      pacman: name={{ item }} state=present
      with_items:
        - emacs-nox
        - sudo
        - git
        - ansible
        - xorg-server
        - xorg-xinit
        - xf86-video-nouveau
        - gnome
        - gnome-keyring
        - wpa_supplicant
        - wireless_tools
        - networkmanager
        - network-manager-applet
        - firefox

    - name: Set passwordless sudo for wheel group
      lineinfile: >
        dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
        line="%wheel ALL=(ALL) NOPASSWD:ALL"
        state=present
        create=yes
        validate="visudo -cf %s"

    - name: Set locale
      lineinfile: >
        dest=/etc/locale.conf owner=root group=root mode=644
        line="LANG=en_US.UTF-8"
        state=present
        create=yes

    - name: Ensure dhcpcd is not enabled or running
      service: >
        name=dhcpcd
        enabled=no
        state=stopped

    - name: Ensure NetworkManager is enabled and running
      service: >
        name=NetworkManager
        enabled=yes
        state=started
