---
- hosts: all
  remote_user: root
  tasks:
    - name: Update package cache
      pacman: update_cache=yes

    - name: Install packages
      pacman: name={{ item }} state=present
      with_items:
        - emacs-nox
        - sudo
        - git
        - ansible
        - xorg-server
        - xorg-xinit
        - xf86-video-nouveau
        - gnome
        - networkmanager
        - network-manager-applet

    - name: Add passwordless wheel to sudoers
      lineinfile: >
        dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
        line="%wheel ALL=(ALL) NOPASSWD:ALL"
        state=present
        create=yes
        validate="visudo -cf %s"
