# Personal setup for arch
#
# Example usage:
#   ansible-playbook -i localhost, arch.yml --vault-password-file vaultpass.txt

---
- hosts: all
  sudo: yes
  remote_user: root
  vars_files:
    - vault/user.yml
  vars:
    - ansible_python_interpreter: python2
    - include_proprietary: yes
  tasks:
    - name: Update package cache
      pacman: update_cache=yes

    - name: Install packages
      pacman: name={{ item }} state=present
      with_items:
        - emacs-nox
        - wget
        - sudo
        - zsh
        - tmux
        - git
        - ansible
        - python2-pip
        - xorg-server
        - xorg-xinit
        - xorg-xrandr
        - wayland
        - xorg-server-xwayland
        - xf86-video-nouveau
        - gnome
        - gnome-keyring
        - wpa_supplicant
        - wireless_tools
        - networkmanager
        - network-manager-applet
        - keepassx
        - firefox
        - chromium

    # These are packages which include proprietary software.
    # They're included since they're pretty much necessary for
    # daily operation, and should be periodically revisited for
    # viable alternatives and/or deprecation.
    - name: Install proprietary packages
      pacman: name={{ item }} state=present
      with_items:
        - flashplugin
      when: include_proprietary

    - name: Ensure dhcpcd is not enabled or running
      service: >
        name=dhcpcd
        enabled=no
        state=stopped

    - name: Ensure NetworkManager is enabled and running
      service: >
        name=NetworkManager
        enabled=yes
        state=started

    - name: Set passwordless sudo for wheel group
      lineinfile: >
        dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
        line="%wheel ALL=(ALL) NOPASSWD:ALL"
        state=present
        create=yes
        validate="visudo -cf %s"

    - name: Set locale
      lineinfile: >
        dest=/etc/locale.conf owner=root group=root mode=644
        line="LANG=en_US.UTF-8"
        state=present
        create=yes

    - name: Create user
      user: >
        name={{ user.name }}
        password={{ user.password }}
        state=present
        shell=/bin/zsh
        group=users
        groups=wheel

    - name: Install AUR packages
      sudo: yes
      sudo_user: "{{ user }}"
      command: aurget -S {{ item }} --noedit --nodiscard --noconfirm --deps
      args:
        chdir: /tmp
      with_items:
        - heroku-toolbelt

    - name: Install oh-my-zsh in home directory
      sudo: yes
      sudo_user: "{{ user }}"
      shell: sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
      args:
        chdir: "/home/{{ user }}"
        creates: "/home/{{ user }}/.oh-my-zsh"
      ignore_errors: yes

    - name: Register default shell
      shell: "echo $shell"
      register: default_shell
      changed_when: no
      sudo: no

    - name: Make zsh the default shell
      shell: chsh -s /bin/bash
      when: default_shell.stdout.find("/bin/zsh") == -1
