# Personal setup for arch
#
# Example usage:
#   ansible-playbook -i localhost, arch.yml --vault-password-file vaultpass.txt

---
- hosts: all
  sudo: yes
  remote_user: root
  vars_files:
    - vault/user.yml
  roles:
    - role: arch
      tags: arch
    - role: zsh
      tags: zsh
