- name: Install packages
  pacman: name=zsh state=present

- block:
    - name: Install oh-my-zsh in home directory
      git: >
        repo=https://raw.github.com/robbyrussell/oh-my-zsh.git
        dest={{ user.home }}/.oh-my-zsh

    - name: Template zshrc
      template: >
        src=.zshrc.j2
        dest={{ user.home }}/.zshrc
  sudo: yes
  sudo_user: "{{ user.name }}"

- name: Register default shell
  shell: "echo $shell"
  register: default_shell
  changed_when: no
  sudo: no

- name: Make zsh the default shell
  shell: chsh -s /bin/bash
  when: default_shell.stdout.find("/bin/zsh") == -1
