- name: Install packages
  pacman: name=zsh state=present

- block:
    - name: Install oh-my-zsh in home directory
      git: >
        repo=https://raw.github.com/robbyrussell/oh-my-zsh.git
        dest={{ user.home }}/.oh-my-zsh

    - name: Template zshrc
      template: >
        src=.zshrc.j2
        dest={{ user.home }}/.zshrc
  sudo: yes
  sudo_user: "{{ user.name }}"

- name: Register default shell
  shell: "echo $shell"
  register: default_shell
  changed_when: no
  sudo: no

- name: Make zsh the default shell
  shell: chsh -s /bin/bash {{ user.name }}
  when: default_shell.stdout.find("/bin/zsh") == -1

- name: Create custom themes directory
  file: >
    path={{ user.home }}/.oh-my-zsh/custom/themes
    state=directory

- name: Install powerlevel9k theme
  git: >
    repo=https://github.com/bhilburn/powerlevel9k.git
    dest={{ user.home }}/.oh-my-zsh/custom/themes/powerlevel9k

- name: Clone powerline fonts repo
  git: >
    repo=https://github.com/powerline/fonts.git
    dest=/tmp/fonts

- name: Install powerline fonts
  command: /tmp/fonts/install.sh
  args:
    creates: "{{ user.home }}/.fonts"
  sudo: yes
  sudo_user: "{{ user.name }}"
