- name: Install expac
  pacman: name=expac state=present

- block:
    - name: Download build file archives
      command: >
        wget https://aur4.archlinux.org/cgit/aur.git/snapshot/{{ item }}.tar.gz
      args:
        chdir: /tmp
        creates: "/tmp/{{ item }}.tar.gz"
      with_items: pacaur_packages

    - name: Unpack archives
      unarchive: >
        copy=no
        src=/tmp/{{ item }}.tar.gz
        dest=/tmp
      with_items: pacaur_packages
    
    - name: Build the packages
      command: makepkg -i --noconfirm
      args:
        chdir: "/tmp/{{ item }}"
      with_items: pacaur_packages
  become: yes
  become_user: "{{ user.name }}"
