- name: Update package cache
  pacman: update_cache=yes

- name: Install packages
  pacman: name={{ item }} state=present
  with_items: packages

# These are packages which include proprietary software.
# They're included since they're pretty much necessary for
# daily operation, and should be periodically revisited for
# viable alternatives and/or deprecation.
- name: Install proprietary packages
  pacman: name={{ item }} state=present
  with_items:
    - flashplugin
  when: include_proprietary

- name: Ensure dhcpcd is not enabled or running
  service: >
    name=dhcpcd
    enabled=no
    state=stopped

- name: Ensure services are enabled and running
  service: >
    name={{ item }}
    enabled=yes
    state=started
  with_items: services

- name: Set passwordless sudo for wheel group
  lineinfile: >
    dest=/etc/sudoers.d/wheel owner=root group=root mode=0440
    line="%wheel ALL=(ALL) NOPASSWD:ALL"
    state=present
    create=yes
    validate="visudo -cf %s"

- name: Set locale
  lineinfile: >
    dest=/etc/locale.conf owner=root group=root mode=644
    line="LANG=en_US.UTF-8"
    state=present
    create=yes

- name: Drop VirtualBox module config
  template: >
    src=virtualbox.conf.j2
    dest=/etc/modules-load.d/virtualbox.conf

- name: Enable VirtualBox kernel modules
  modprobe: name={{ item }} state=present
  with_items: virtualbox_modules

- name: Create user
  user: >
    name={{ user.name }}
    password={{ user.password }}
    state=present
    shell=/bin/zsh
    group=users
    groups=wheel,docker

# Drop user config on remote machine
- block:
    # This is a template so that it'll replace any existing config
    # so long as it's different.
    - name: Drop gpg config
      template: >
        src=gpg.conf
        dest={{ user.home }}/.gnupg/gpg.conf
        force=yes

    - name: Drop xinitrc
      copy: >
        src=.xinitrc
        dest="{{ user.home }}/.xinitrc"
  become: yes
  become_user: "{{ user.name }}"
